# -*- coding: utf-8 -*-
"""chapter 14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xAGfWdHJqiZ8dc0iojgt2fAyraWO5rvD

Please run those two cells before running the Notebook!

As those plotting settings are standard throughout the book, we do not show them in the book every time we plot something.
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
# %config InlineBackend.figure_format = "retina"

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
from pandas.core.common import SettingWithCopyWarning
warnings.simplefilter(action="ignore", category=FutureWarning)
warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

# feel free to modify, for example, change the context to "notebook"
sns.set_theme(context="talk", style="whitegrid",
              palette="colorblind", color_codes=True,
              rc={"figure.figsize": [12, 8]})

"""# Chapter 14 - Advanced Concepts for ML Projects

## 14.1 Exploring ensemble classifiers

### Getting Ready

Prepare the Pipeline:
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from chapter_14_utils import performance_evaluation_report

df = pd.read_csv("../Datasets/credit_card_default.csv", na_values="")

X = df.copy()
y = X.pop("default_payment_next_month")

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    stratify=y,
                                                    random_state=42)

num_features = X_train.select_dtypes(include="number").columns.to_list()
cat_features = X_train.select_dtypes(include="object").columns.to_list()

num_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

cat_list = [list(X_train[col].dropna().unique()) for col in cat_features]

cat_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(categories=cat_list, sparse=False,
                             handle_unknown="error", drop="first"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("numerical", num_pipeline, num_features),
        ("categorical", cat_pipeline, cat_features)
    ],
    remainder="drop"
)

tree_pipeline = Pipeline(
    steps=[("preprocessor", preprocessor),
           ("classifier", DecisionTreeClassifier(random_state=42))]
)

tree_pipeline.fit(X_train, y_train)

LABELS = ["No Default", "Default"]
tree_perf = performance_evaluation_report(tree_pipeline, X_test,
                                          y_test, labels=LABELS,
                                          show_plot=True,
                                          show_pr_curve=True)

print(f"Recall: {tree_perf['recall']:.4f}")

"""### How to do it...

1. Import the libraries:
"""

from sklearn.ensemble import (RandomForestClassifier,
                              GradientBoostingClassifier)
from xgboost.sklearn import XGBClassifier
from lightgbm import LGBMClassifier
from chapter_14_utils import performance_evaluation_report

"""2. Define and fit the Random Forest pipeline:"""

rf = RandomForestClassifier(random_state=42)
rf_pipeline = Pipeline(
    steps=[("preprocessor", preprocessor),
           ("classifier", rf)]
)

rf_pipeline.fit(X_train, y_train)
rf_perf = performance_evaluation_report(rf_pipeline, X_test,
                                        y_test, labels=LABELS,
                                        show_plot=True,
                                        show_pr_curve=True)

print(f"Recall: {rf_perf['recall']:.4f}")

sns.despine()
# plt.savefig("images/figure_14_1", dpi=200)

"""3. Define and fit the Gradient Boosted Trees pipeline:"""

gbt = GradientBoostingClassifier(random_state=42)
gbt_pipeline = Pipeline(
    steps=[("preprocessor", preprocessor),
           ("classifier", gbt)]
)

gbt_pipeline.fit(X_train, y_train)
gbt_perf = performance_evaluation_report(gbt_pipeline, X_test,
                                         y_test, labels=LABELS,
                                         show_plot=True,
                                         show_pr_curve=True)

print(f"Recall: {gbt_perf['recall']:.4f}")

sns.despine()
# plt.savefig("images/figure_14_2", dpi=200)

"""4. Define and fit an XGBoost pipeline:"""

xgb = XGBClassifier(random_state=42)
xgb_pipeline = Pipeline(
    steps=[("preprocessor", preprocessor),
           ("classifier", xgb)]
)

xgb_pipeline.fit(X_train, y_train)
xgb_perf = performance_evaluation_report(xgb_pipeline, X_test,
                                         y_test, labels=LABELS,
                                         show_plot=True,
                                         show_pr_curve=True)

print(f"Recall: {xgb_perf['recall']:.4f}")

sns.despine()
# plt.savefig("images/figure_14_3", dpi=200)

"""5. Define and fit the LightGBM pipeline:"""

lgbm = LGBMClassifier(random_state=42)
lgbm_pipeline = Pipeline(
    steps=[("preprocessor", preprocessor),
           ("classifier", lgbm)]
)

lgbm_pipeline.fit(X_train, y_train)
lgbm_perf = performance_evaluation_report(lgbm_pipeline, X_test,
                                          y_test, labels=LABELS,
                                          show_plot=True,
                                          show_pr_curve=True)

print(f"Recall: {lgbm_perf['recall']:.4f}")

sns.despine()
# plt.savefig("images/figure_14_4", dpi=200)

"""### There's more

Below we go over the most important hyperparameters of the considered models and show a possible way of tuning them using Randomized Search. With more complex models, the training time is significantly longer than with the basic Decision Tree. That is why we need to find a balance between the time we want to spend on tuning the hyperparameters and the expected results. Also, bear in mind that changing the values of some parameters (such as learning rate or the number of estimators) can itself influence the training time of the models.

To have the results in a reasonable amount of time, we used the Randomized Search with 100 different sets of hyperparameters for each model (the number of actually fitted models is higher due to cross-validation).

For a complete list of hyperparameters and their meaning, please refer to the corresponding documentations.

As in the previous chapter, we used recall as the evaluation metric.
"""

from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from sklearn import metrics
import numpy as np

N_SEARCHES = 100
k_fold = StratifiedKFold(5, shuffle=True, random_state=42)

"""**Random Forest**

When tuning the Random Forest classifier, we look at the following hyperparameters (there are more available for tuning):
* `n_estimators` - the number of decision trees in a forest. The goal is to find a balance between improved accuracy and computational cost.
* `max_features` - the maximum number of features considered for splitting a node. The default is the square root of the number of features. When None, all features are considered.
* `max_depth` - the maximum number of levels in each decision tree
* `min_samples_split` - the minimum number of observations required to split each node. When set to high it may cause underfitting, as the trees will not split enough times.
* `min_samples_leaf` - the minimum number of data points allowed in a leaf. Too small a value might cause overfitting, while large values might prevent the tree from growing and cause underfitting.
* `bootstrap` - whether to use bootstrapping for each tree in the forest

We define the grid below:
"""

rf_param_grid = {
    "classifier__n_estimators": np.linspace(100, 500, 5, dtype=int),
    "classifier__max_features": ["log2", "sqrt", None],
    "classifier__max_depth": np.arange(3, 11, 1, dtype=int),
    "classifier__min_samples_split": [2, 5, 10],
    "classifier__min_samples_leaf": np.arange(1, 51, 2, dtype=int),
    "classifier__bootstrap": [True, False]
}

"""And use the randomized search to tune the classifier:"""

rf_rs =  RandomizedSearchCV(rf_pipeline, rf_param_grid, scoring="recall",
                            cv=k_fold, n_jobs=-1, verbose=1,
                            n_iter=N_SEARCHES, random_state=42)

rf_rs.fit(X_train, y_train)

print(f"Best parameters: {rf_rs.best_params_}")
print(f"Recall (Training set): {rf_rs.best_score_:.4f}")
print(f"Recall (Test set): {metrics.recall_score(y_test, rf_rs.predict(X_test)):.4f}")

rf_rs_perf = performance_evaluation_report(rf_rs, X_test,
                                           y_test, labels=LABELS,
                                           show_plot=True,
                                           show_pr_curve=True)

"""**Gradient Boosted Trees**

As Gradient Boosted Trees are also an ensemble method built on top of decision trees, a lot of the parameters are the same as in the case of the Random Forest. The new one is the learning rate, which is used in the gradient descent algorithm to control the rate of descent towards the minimum of the loss function. When tuning the tree manually, we should consider this hyperparameter together with the number of estimators, as reducing the learning rate (the learning is slower), while increasing the number of estimators can increase the computation time significantly.

We define the grid as follows:
"""

gbt_param_grid = {
    "classifier__n_estimators": np.linspace(100, 500, 5, dtype=int),
    "classifier__learning_rate": np.arange(0.05, 0.31, 0.05),
    "classifier__max_depth": np.arange(3, 11, 1, dtype=int),
    "classifier__min_samples_split": np.linspace(0.1, 0.5, 12),
    "classifier__min_samples_leaf": np.arange(1, 51, 2, dtype=int),
    "classifier__max_features":["log2", "sqrt", None]
}

"""And run the randomized search:"""

gbt_rs =  RandomizedSearchCV(gbt_pipeline, gbt_param_grid, scoring="recall",
                             cv=k_fold, n_jobs=-1, verbose=1,
                             n_iter=N_SEARCHES, random_state=42)

gbt_rs.fit(X_train, y_train)

print(f"Best parameters: {gbt_rs.best_params_}")
print(f"Recall (Training set): {gbt_rs.best_score_:.4f}")
print(f"Recall (Test set): {metrics.recall_score(y_test, gbt_rs.predict(X_test)):.4f}")

gbt_rs_perf = performance_evaluation_report(gbt_rs, X_test,
                                            y_test, labels=LABELS,
                                            show_plot=True,
                                            show_pr_curve=True)

"""**XGBoost**

The scikit-learn API of XGBoost makes sure that the hyperparameters are named similarly to their equivalents other scikit-learn's classifiers. So the XGBoost native eta hyperparameter is called learning_rate in scikit-learn's API.

The new hyperparameters we consider for this example are:
* `min_child_weight` - indicates the minimum sum of weights of all observations required in a child. This hyperparameter is used for controlling overfitting. Cross-validation should be used for tuning.
* `colsample_bytree` - indicates the fraction of columns to be randomly sampled for each tree.

We define the grid as:
"""

xgb_param_grid = {
    "classifier__n_estimators": np.linspace(100, 500, 5, dtype=int),
    "classifier__learning_rate": np.arange(0.05, 0.31, 0.05),
    "classifier__max_depth": np.arange(3, 11, 1, dtype=int),
    "classifier__min_child_weight": np.arange(1, 8, 1, dtype=int),
    "classifier__colsample_bytree": np.linspace(0.3, 1, 7)
}

"""For defining ranges of parameters that are restricted (such as colsample_bytree which cannot be higher than 1.0) it is better to use `np.linspace` rather than `np.arange`, because the latter allows for some inconsistencies when the step is defined as floating-point. For example, the last value might be 1.0000000002, which then causes an error while training the classifier."""

xgb_rs =  RandomizedSearchCV(xgb_pipeline, xgb_param_grid, scoring="recall",
                             cv=k_fold, n_jobs=-1, verbose=1,
                             n_iter=N_SEARCHES, random_state=42)

xgb_rs.fit(X_train, y_train)

print(f"Best parameters: {xgb_rs.best_params_}")
print(f"Recall (Training set): {xgb_rs.best_score_:.4f}")
print(f"Recall (Test set): {metrics.recall_score(y_test, xgb_rs.predict(X_test)):.4f}")

xgb_rs_perf = performance_evaluation_report(xgb_rs, X_test,
                                            y_test, labels=LABELS,
                                            show_plot=True,
                                            show_pr_curve=True)

"""**LightGBM**

We tune the same parameters as in XGBoost, though more is definitely possible and encouraged. The grid is defined as follows:
"""

lgbm_param_grid = {
    "classifier__n_estimators": np.linspace(100, 500, 5, dtype=int),
    "classifier__learning_rate": np.arange(0.05, 0.31, 0.05),
    "classifier__max_depth": np.arange(3, 11, 1, dtype=int),
    "classifier__colsample_bytree": np.linspace(0.3, 1, 7)
}

lgbm_rs =  RandomizedSearchCV(lgbm_pipeline, lgbm_param_grid, scoring="recall",
                              cv=k_fold, n_jobs=-1, verbose=1,
                              n_iter=N_SEARCHES, random_state=42)

lgbm_rs.fit(X_train, y_train)

print(f"Best parameters: {lgbm_rs.best_params_}")
print(f"Recall (Training set): {lgbm_rs.best_score_:.4f}")
print(f"Recall (Test set): {metrics.recall_score(y_test, lgbm_rs.predict(X_test)):.4f}")

lgbm_rs_perf = performance_evaluation_report(lgbm_rs, X_test,
                                             y_test, labels=LABELS,
                                             show_plot=True,
                                             show_pr_curve=True)

"""Below we present a summary of all the classifiers we have considered in this exercise."""

results_dict = {
    "decision_tree_baseline": tree_perf,
    "random_forest": rf_perf,
    "random_forest_rs": rf_rs_perf,
    "gradient_boosted_trees": gbt_perf,
    "gradient_boosted_trees_rs": gbt_rs_perf,
    "xgboost": xgb_perf,
    "xgboost_rs": xgb_rs_perf,
    "light_gbm": lgbm_perf,
    "light_gbm_rs": lgbm_rs_perf
}

results_comparison = pd.DataFrame(results_dict).T
results_comparison

results_comparison.to_csv("results_comparison.csv")

"""## 14.2 Exploring alternative approaches to encoding categorical features

### Getting Ready

Prepare the Pipeline:
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from chapter_14_utils import performance_evaluation_report
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("../Datasets/credit_card_default.csv", na_values="")

X = df.copy()
y = X.pop("default_payment_next_month")

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    stratify=y,
                                                    random_state=42)

num_features = X_train.select_dtypes(include="number").columns.to_list()
cat_features = X_train.select_dtypes(include="object").columns.to_list()

num_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

cat_list = [list(X_train[col].dropna().unique()) for col in cat_features]

cat_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("cat_encoding", OneHotEncoder(categories=cat_list, sparse=False,
                             handle_unknown="error", drop="first"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("numerical", num_pipeline, num_features),
        ("categorical", cat_pipeline, cat_features)
    ],
    remainder="drop"
)

rf_pipeline = Pipeline(
    steps=[("preprocessor", preprocessor),
           ("classifier", RandomForestClassifier(random_state=42))]
)

rf_pipeline.fit(X_train, y_train)

LABELS = ["No Default", "Default"]
rf_perf = performance_evaluation_report(rf_pipeline, X_test,
                                        y_test, labels=LABELS,
                                        show_plot=True,
                                        show_pr_curve=True)

rf_perf

print(f"Recall: {rf_perf['recall']:.4f}")

"""### How to do it...

1. Import the libraries:
"""

import category_encoders as ce
from sklearn.base import clone

"""2. Fit the pipeline using target encoding:"""

pipeline_target_enc = clone(rf_pipeline)
pipeline_target_enc.set_params(
    preprocessor__categorical__cat_encoding=ce.TargetEncoder()
)

pipeline_target_enc.fit(X_train, y_train)
target_enc_perf = performance_evaluation_report(
    pipeline_target_enc, X_test,
    y_test, labels=LABELS,
    show_plot=True,
    show_pr_curve=True
)
print(f"Recall: {target_enc_perf['recall']:.4f}")

sns.despine()
# plt.savefig("images/figure_14_10", dpi=200)

"""3. Fit the pipeline using Leave One Out encoding:"""

pipeline_loo_enc = clone(rf_pipeline)
pipeline_loo_enc.set_params(
    preprocessor__categorical__cat_encoding=ce.LeaveOneOutEncoder()
)

pipeline_loo_enc.fit(X_train, y_train)
loo_enc_perf = performance_evaluation_report(
    pipeline_loo_enc, X_test,
    y_test, labels=LABELS,
    show_plot=True,
    show_pr_curve=True
)
print(f"Recall: {loo_enc_perf['recall']:.4f}")

sns.despine()
# plt.savefig("images/figure_14_11", dpi=200)

# testing if we can improve the performance by adding random noise

pipeline_loo_enc = clone(rf_pipeline)
pipeline_loo_enc.set_params(
    preprocessor__categorical__cat_encoding=ce.LeaveOneOutEncoder(sigma=0.05, random_state=42)
)

pipeline_loo_enc.fit(X_train, y_train)
loo_enc_perf = performance_evaluation_report(
    pipeline_loo_enc, X_test,
    y_test, labels=LABELS,
    show_plot=True,
    show_pr_curve=True
)
print(f"Recall: {loo_enc_perf['recall']:.4f}")

sns.despine()

"""4. Fit the pipeline using Weight of Evidence encoding:"""

pipeline_woe_enc = clone(rf_pipeline)
pipeline_woe_enc.set_params(
    preprocessor__categorical__cat_encoding=ce.WOEEncoder()
)

pipeline_woe_enc.fit(X_train, y_train)
woe_enc_perf = performance_evaluation_report(
    pipeline_woe_enc, X_test,
    y_test, labels=LABELS,
    show_plot=True,
    show_pr_curve=True
)
print(f"Recall: {woe_enc_perf['recall']:.4f}")

sns.despine()
# plt.savefig("images/figure_14_12", dpi=200)

"""### There's more

Experimenting with different values of `min_samples_leaf` and `smoothing` for target encoding:
"""

for smoothing in [0, 1, 2, 5, 10]:
    for min_smpl_leaf in [1, 5]:

        pipeline_target_enc = clone(rf_pipeline)
        pipeline_target_enc.set_params(
            preprocessor__categorical__cat_encoding=ce.TargetEncoder(min_samples_leaf=min_smpl_leaf,
                                                                     smoothing=smoothing)
        )

        pipeline_target_enc.fit(X_train, y_train)
        target_enc_perf = performance_evaluation_report(pipeline_target_enc, X_test,
                                                        y_test, labels=LABELS,
                                                        show_plot=False,
                                                        show_pr_curve=False)
        print(f"Smoothing <{smoothing}> Min Samples Leaf <{min_smpl_leaf}> --- Recall: {target_enc_perf['recall']:.4f}")

"""### Bonus: small examples

Below you can find some self-contained examples which show how the encoding algorithms work.
For your convenience, they are the same as the ones shown as examples in the book.
"""

import category_encoders as ce
import pandas as pd

"""**Target encoding**"""

# binary target
df = pd.DataFrame({
   "category":["a", "a", "b", "b", "b"],
   "target":[1,0,1,1,0]})

X = df.drop("target", axis = 1)
y = df.drop("category", axis = 1)

encoder = ce.TargetEncoder(smoothing=0)
encoder.fit_transform(X, y["target"])

# continuous target
df = pd.DataFrame({
   "category":["a", "a", "b", "b", "b"],
   "target":[5,3,1,3,6]})

X = df.drop("target", axis = 1)
y = df.drop("category", axis = 1)

encoder = ce.TargetEncoder(smoothing=0)
encoder.fit_transform(X, y["target"])

"""**Leave One Out encoding**"""

df = pd.DataFrame({
   "category":["a", "a", "b", "b", "b"],
   "target":[1,0,1,1,0]})

X = df.drop("target", axis = 1)
y = df.drop("category", axis = 1)

encoder = ce.LeaveOneOutEncoder()
encoder.fit_transform(X, y["target"])

"""**Weight of Evidence encoding**"""

df = pd.DataFrame({
   "category":["a", "a", "b", "b", "b"],
   "target":[1,0,1,1,0]})

X = df.drop("target", axis = 1)
y = df.drop("category", axis = 1)

encoder = ce.WOEEncoder(regularization=0)
encoder.fit_transform(X, y["target"])

"""**Binary encoding**"""

import numpy as np

df = pd.DataFrame({
   "category":[str(x) for x in np.random.normal(size=100)]
})

encoder = ce.BinaryEncoder()
encoder.fit_transform(df).shape

"""## 14.3 Investigating different approaches to handling imbalanced data

### How to do it...

1. Import the libraries:
"""

import pandas as pd
from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import RobustScaler

from imblearn.over_sampling import RandomOverSampler, SMOTE, ADASYN
from imblearn.under_sampling import RandomUnderSampler
from imblearn.ensemble import BalancedRandomForestClassifier

from chapter_14_utils import performance_evaluation_report

"""2. Load and prepare data:"""

RANDOM_STATE = 42

df = pd.read_csv("../Datasets/credit_card_fraud.csv")

X = df.copy().drop(columns=["Time"])
y = X.pop("Class")

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=RANDOM_STATE
)

y.value_counts(normalize=True)

"""3. Scale the features using `RobustScaler`"""

robust_scaler = RobustScaler()

X_train = robust_scaler.fit_transform(X_train)
X_test = robust_scaler.transform(X_test)

"""4. Train the baseline model:"""

rf = RandomForestClassifier(
    random_state=RANDOM_STATE, n_jobs=-1
)
rf.fit(X_train, y_train)

rf_perf = performance_evaluation_report(rf, X_test, y_test,
                                        show_plot=True,
                                        show_pr_curve=True)

rf_perf

"""5. Undersample the training data and train a Random Forest Classifier:"""

rus = RandomUnderSampler(random_state=RANDOM_STATE)
X_rus, y_rus = rus.fit_resample(X_train, y_train)
print(f"The new class proportions are: {dict(Counter(y_rus))}")

rf.fit(X_rus, y_rus)
rf_rus_perf = performance_evaluation_report(rf, X_test, y_test,
                                            show_plot=True,
                                            show_pr_curve=True)

rf_rus_perf

"""6. Oversample the training data and train a Random Forest Classifier:"""

ros = RandomOverSampler(random_state=RANDOM_STATE)
X_ros, y_ros = ros.fit_resample(X_train, y_train)
print(f"The new class proportions are: {dict(Counter(y_ros))}")

rf.fit(X_ros, y_ros)
rf_ros_perf = performance_evaluation_report(rf, X_test, y_test,
                                            show_plot=True,
                                            show_pr_curve=True)

rf_ros_perf

"""7. Oversample the training data using SMOTE:"""

smote = SMOTE(random_state=RANDOM_STATE)
X_smote, y_smote = smote.fit_resample(X_train, y_train)
print(f"The new class proportions are: {dict(Counter(y_smote))}")

rf.fit(X_smote, y_smote)
rf_smote_perf = performance_evaluation_report(
    rf, X_test, y_test,
    show_plot=True,
    show_pr_curve=True
)

rf_smote_perf

"""8. Oversample the training data using ADASYN:"""

adasyn = ADASYN(random_state=RANDOM_STATE)
X_adasyn, y_adasyn = adasyn.fit_resample(X_train, y_train)
print(f"The new class proportions are: {dict(Counter(y_adasyn))}")

rf.fit(X_adasyn, y_adasyn)
rf_adasyn_perf = performance_evaluation_report(
    rf, X_test, y_test,
    show_plot=True,
    show_pr_curve=True
)

rf_adasyn_perf

"""9. Use sample weights in the Random Forest Classifier:"""

rf_cw = RandomForestClassifier(random_state=RANDOM_STATE,
                               class_weight="balanced",
                               n_jobs=-1)
rf_cw.fit(X_train, y_train)

rf_cw_perf = performance_evaluation_report(
    rf_cw, X_test, y_test,
    show_plot=True,
    show_pr_curve=True
)

rf_cw_perf

"""10. Train the `BalancedRandomForestClassifier`:"""

balanced_rf = BalancedRandomForestClassifier(
    random_state=RANDOM_STATE
)

balanced_rf.fit(X_train, y_train)
balanced_rf_perf = performance_evaluation_report(
    balanced_rf, X_test, y_test,
    show_plot=True,
    show_pr_curve=True
)

"""11. Train the `BalancedRandomForestClassifier` with balanced classes:"""

balanced_rf_cw = BalancedRandomForestClassifier(
    random_state=RANDOM_STATE,
    class_weight="balanced",
    n_jobs=-1
)

balanced_rf_cw.fit(X_train, y_train)
balanced_rf_cw_perf = performance_evaluation_report(
    balanced_rf_cw, X_test, y_test,
    show_plot=True,
    show_pr_curve=True
)

"""12. Combine the results in a DataFrame:"""

performance_results = {
    "random_forest": rf_perf,
    "undersampled rf": rf_rus_perf,
    "oversampled_rf": rf_ros_perf,
    "smote": rf_smote_perf,
    "adasyn": rf_adasyn_perf,
    "random_forest_cw": rf_cw_perf,
    "balanced_random_forest": balanced_rf_perf,
    "balanced_random_forest_cw": balanced_rf_cw_perf,
}
pd.DataFrame(performance_results).round(4).T

"""## 14.4 Leveraging the wisdom of the crowds with stacked ensembles

### How to do it...

1. Import the libraries:
"""

import pandas as pd
from sklearn.model_selection import (train_test_split,
                                     StratifiedKFold)
from sklearn.metrics import recall_score
from sklearn.preprocessing import RobustScaler

from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import StackingClassifier

"""2. Load and preprocess data:"""

RANDOM_STATE = 42

df = pd.read_csv("../Datasets/credit_card_fraud.csv")

X = df.copy().drop(columns=["Time"])
y = X.pop("Class")

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=RANDOM_STATE
)

robust_scaler = RobustScaler()
X_train = robust_scaler.fit_transform(X_train)
X_test = robust_scaler.transform(X_test)

"""3. Define a list of base models:"""

base_models = [
    ("dec_tree", DecisionTreeClassifier(random_state=RANDOM_STATE)),
    ("log_reg", LogisticRegression(random_state=RANDOM_STATE)),
    ("svc", SVC(random_state=RANDOM_STATE)),
    # ("knn", KNeighborsClassifier()),
    ("naive_bayes", GaussianNB())
]

"""4. Train the selected models and calculate recall using the test set:"""

for model_tuple in base_models:
    clf = model_tuple[1]
    if "n_jobs" in clf.get_params().keys():
        clf.set_params(n_jobs=-1)
    clf.fit(X_train, y_train)
    recall = recall_score(y_test, clf.predict(X_test))
    print(f"{model_tuple[0]}'s recall score: {recall:.4f}")

"""5. Define, fit and evaluate the stacked ensemble:"""

cv_scheme = StratifiedKFold(n_splits=5,
                            shuffle=True,
                            random_state=RANDOM_STATE)
meta_model = LogisticRegression(random_state=RANDOM_STATE)

stack_clf = StackingClassifier(
    base_models,
    final_estimator=meta_model,
    cv=cv_scheme,
    n_jobs=-1
)
stack_clf.fit(X_train, y_train)

recall = recall_score(y_test, stack_clf.predict(X_test))
print(f"The stacked ensemble's recall score: {recall:.4f}")

"""6. Improve the stacking ensemble with additional features and a more complex meta model:"""

meta_model = RandomForestClassifier(random_state=RANDOM_STATE)
stack_clf = StackingClassifier(
    base_models,
    final_estimator=meta_model,
    cv=cv_scheme,
    passthrough=True,
    n_jobs=-1
)
stack_clf.fit(X_train, y_train)

recall = recall_score(y_test, stack_clf.predict(X_test))
print(f"The stacked ensemble's recall score: {recall:.4f}")

"""### There's more"""

level_0_names = [f"{model[0]}_pred" for model in base_models]

level_0_df = pd.DataFrame(
    stack_clf.transform(X_train),
    columns=level_0_names + list(X.columns)
)

level_0_df.head()

level_0_df[level_0_names].describe().T

"""## 14.5 Bayesian hyperparameter optimization

### How to do it...

1. Load the libraries:
"""

import pickle
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.model_selection import (cross_val_score,
                                     StratifiedKFold)
from lightgbm import LGBMClassifier

from hyperopt import hp, fmin, tpe, STATUS_OK, Trials, space_eval
from hyperopt.pyll import scope
from hyperopt.pyll.stochastic import sample

from chapter_14_utils import performance_evaluation_report

"""2. Define parameters for later use:"""

N_FOLDS = 5
MAX_EVALS = 200
RANDOM_STATE = 42
EVAL_METRIC = "recall"
DEBUG = False

"""3. Load and prepare the data:"""

df = pd.read_csv("../Datasets/credit_card_fraud.csv")

X = df.copy().drop(columns=["Time"])
y = X.pop("Class")

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=RANDOM_STATE
)

"""4. Train the benchmark LightGBM model with the default hyperparameters:"""

clf = LGBMClassifier(random_state=RANDOM_STATE)
clf.fit(X_train, y_train)

benchmark_perf = performance_evaluation_report(
    clf, X_test, y_test,
    show_plot=True,
    show_pr_curve=True
)
print(f'Recall: {benchmark_perf["recall"]:.4f}')

sns.despine()
# plt.savefig("images/figure_14_18", dpi=200)

"""5. Define the objective function:"""

def objective(params, n_folds=N_FOLDS,
              random_state=RANDOM_STATE,
              metric=EVAL_METRIC):

    # useful for debugging
    if DEBUG:
        print(params)

    model = LGBMClassifier(**params, random_state=random_state)
    k_fold = StratifiedKFold(n_folds, shuffle=True,
                             random_state=random_state)

    scores = cross_val_score(model, X_train, y_train,
                             cv=k_fold, scoring=metric)
    loss = -1 * scores.mean()

    return {"loss": loss, "params": params, "status": STATUS_OK}

"""6. Define the search space:"""

search_space = {
    "n_estimators": hp.choice("n_estimators", [50, 100, 250, 500]),
    "boosting_type": hp.choice(
        "boosting_type", ["gbdt", "dart", "goss"]
    ),
    "is_unbalance": hp.choice("is_unbalance", [True, False]),
    "max_depth": scope.int(hp.uniform("max_depth", 3, 20)),
    "num_leaves": scope.int(hp.quniform("num_leaves", 5, 100, 1)),
    "min_child_samples": scope.int(
        hp.quniform("min_child_samples", 20, 500, 5)
    ),
    "colsample_bytree": hp.uniform("colsample_bytree", 0.3, 1.0),
    "learning_rate": hp.loguniform(
        "learning_rate", np.log(0.01), np.log(0.5)
    ),
    "reg_alpha": hp.uniform("reg_alpha", 0.0, 1.0),
    "reg_lambda": hp.uniform("reg_lambda", 0.0, 1.0),
}

sample(search_space)

"""7. Find the best hyperparameters using Bayesian HPO:"""

trials = Trials()
best_set = fmin(fn=objective,
                space=search_space,
                algo=tpe.suggest,
                max_evals=MAX_EVALS,
                trials=trials,
                rstate=np.random.default_rng(RANDOM_STATE))

# store the results in a pickle
pickle.dump(trials, open("light_gbm_200_runs.p", "wb"))

"""8. Inspect the best set of hyperparameters:"""

space_eval(search_space , best_set)

best_set

"""9. Fit a new model using the best hyperparameters:"""

tuned_lgbm = LGBMClassifier(
    **space_eval(search_space, best_set),
    random_state=RANDOM_STATE
)
tuned_lgbm.fit(X_train, y_train)

"""10. Evaluate the fitted model on the test set:"""

tuned_perf = performance_evaluation_report(
    tuned_lgbm, X_test, y_test,
    show_plot=True,
    show_pr_curve=True
)

print(f'Recall: {tuned_perf["recall"]:.4f}')

sns.despine()
# plt.savefig("images/figure_14_19", dpi=200)

"""### There's more

#### Conditional hyperparameter space

1. Define a conditional hyperparameter space:
"""

conditional_search_space = {
    "boosting_type": hp.choice("boosting_type", [
        {"boosting_type": "gbdt",
         "subsample": hp.uniform("gdbt_subsample", 0.5, 1),
         "subsample_freq": scope.int(
            hp.uniform("gdbt_subsample_freq", 1, 20)
         )},
        {"boosting_type": "dart",
         "subsample": hp.uniform("dart_subsample", 0.5, 1),
         "subsample_freq": scope.int(
            hp.uniform("dart_subsample_freq", 1, 20)
         )},
        {"boosting_type": "goss",
         "subsample": 1.0,
         "subsample_freq": 0},
    ]),
    "n_estimators": hp.choice("n_estimators", [50, 100, 250, 500]),
}

# conditional_search_space = {
#     "boosting_type": hp.choice("boosting_type", [
#         {"boosting_type": "gbdt",
#          "subsample": hp.uniform("gdbt_subsample", 0.5, 1),
#          "subsample_freq": scope.int(hp.uniform("gdbt_subsample_freq", 1, 20))},
#         {"boosting_type": "dart",
#          "subsample": hp.uniform("dart_subsample", 0.5, 1),
#          "subsample_freq": scope.int(hp.uniform("dart_subsample_freq", 1, 20))},
#         # {"boosting_type": "rf",
#         #  "subsample": hp.uniform("rf_subsample", 0.5, 1),
#         #  "subsample_freq": scope.int(hp.uniform("rf_subsample_freq", 1, 20))},
#         {"boosting_type": "goss",
#          "subsample": 1.0,
#          "subsample_freq": 0},
#     ]),
#     "n_estimators": hp.choice("n_estimators", [50, 100, 250, 500]),
#     "is_unbalance": hp.choice("is_unbalance", [True, False]),
#     "max_depth": scope.int(hp.uniform("max_depth", 3, 20)),
#     "num_leaves": scope.int(hp.quniform("num_leaves", 5, 100, 1)),
#     "min_child_samples": scope.int(hp.quniform("min_child_samples", 20, 500, 5)),
#     "colsample_bytree": hp.uniform("colsample_bytree", 0.3, 1.0),
#     "learning_rate": hp.loguniform("learning_rate", np.log(0.01), np.log(0.5)),
#     "reg_alpha": hp.uniform("reg_alpha", 0.0, 1.0),
#     "reg_lambda": hp.uniform("reg_lambda", 0.0, 1.0),
# }

# draw from the search space
params = sample(conditional_search_space)
params

# retrieve the conditional parameters, set to default if missing
subsample = params["boosting_type"].get("subsample", 1.0)
subsample_freq = params["boosting_type"].get("subsample_freq", 0)

# fill in the params dict with the conditional values
params["boosting_type"] = params["boosting_type"]["boosting_type"]
params["subsample"] = subsample
params["subsample_freq"] = subsample_freq

params

"""2. Modify the objective function to account for the conditional hyperparameter space:"""

def modified_objective(params, n_folds=N_FOLDS, random_state=RANDOM_STATE, metric=EVAL_METRIC):

    # retrieve the conditional parameters, set to default if missing
    subsample = params["boosting_type"].get("subsample", 1.0)
    subsample_freq = params["boosting_type"].get("subsample_freq", 0)

    # fill in the params dict with the conditional values
    params["boosting_type"] = params["boosting_type"]["boosting_type"]
    params["subsample"] = subsample
    params["subsample_freq"] = subsample_freq

    # useful for debugging
    if DEBUG:
        print(params)

    model = LGBMClassifier(**params, random_state=random_state)
    k_fold = StratifiedKFold(n_folds, shuffle=True,
                             random_state=random_state)

    scores = cross_val_score(model, X_train, y_train,
                             cv=k_fold, scoring=metric)
    loss = -1 * scores.mean()

    return {"loss": loss, "params": params, "status": STATUS_OK}

"""3. Run the Bayesian HPO with the conditional hyperparam space:"""

trials = Trials()
best_set_2 = fmin(fn= modified_objective,
                  space= conditional_search_space,
                  algo= tpe.suggest,
                  max_evals = MAX_EVALS,
                  trials= trials,
                  rstate=np.random.default_rng(RANDOM_STATE))

# store the results in a pickle
pickle.dump(trials, open("light_gbm_200_runs_conditional_space.p", "wb"))

"""4. Inspect the best hyperparameters:"""

space_eval(conditional_search_space , best_set_2)

"""5. Clean up the dictionary before training a model:"""

best_params_2 = space_eval(conditional_search_space , best_set_2)

# retrieve the conditional parameters, set to default if missing
subsample = best_params_2["boosting_type"].get("subsample", 1.0)
subsample_freq = best_params_2["boosting_type"].get("subsample_freq", 0)

# fill in the best_params_2 dict with the conditional values
best_params_2["boosting_type"] = best_params_2["boosting_type"]["boosting_type"]
best_params_2["subsample"] = subsample
best_params_2["subsample_freq"] = subsample_freq

best_params_2

"""6. Train the tuned LightGBM classifier:"""

tuned_lgbm_2 = LGBMClassifier(
    **best_params_2,
    random_state=RANDOM_STATE
)
tuned_lgbm_2.fit(X_train, y_train)

tuned_perf_2 = performance_evaluation_report(tuned_lgbm_2, X_test, y_test,
                                           show_plot=True,
                                           show_pr_curve=True)

print(f'Recall: {tuned_perf_2["recall"]:.4f}')

sns.despine()
# plt.savefig("images/figure_14_20", dpi=200)

"""#### A deep-dive into the explored hyperparameters

0. Load the trials file (if needed):
"""

trials = pickle.load(open("light_gbm_200_runs.p", "rb"))

"""1. Import the additional libraries:"""

from pandas.io.json import json_normalize

"""2. Define a helper function for drawing samples from a hyperparameter search space:"""

def draw_samples(search_space, n_samples=10000):
    samples_list = []

    for _ in range(n_samples):
        samples_list.append(sample(search_space))

    return samples_list

"""3. Plot the distribution of the learning rate:"""

lr_samples = draw_samples(search_space["learning_rate"])

sns.kdeplot(lr_samples, linewidth = 2, shade = True)
plt.title("Distribution of learning rate")
plt.xlabel("Learning rate")
plt.ylabel("Density")

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_21", dpi=200)

"""4. Create the KDE plot of `min_child_samples`:"""

mcs_samples = draw_samples(search_space["min_child_samples"])

sns.kdeplot(mcs_samples, linewidth = 2, shade = True)
plt.title("Distribution of min_child_samples")
plt.xlabel("min_child_samples")
plt.ylabel("Density")

plt.tight_layout()
sns.despine()

"""5. Plot the distribution of `min_child_samples`:

We could also use the `sns.countplot`, however, we only wanted to plot a restricted range of values to keep the plot readable.
"""

(
    pd.Series(mcs_samples)
    .value_counts()
    .sort_index()
    .head(20)
    .plot(kind="bar",
          title="Distribution of min_child_samples")
);

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_22", dpi=200)

"""6. Store all the information from `trials.results` into a DataFrame:"""

results_df = pd.DataFrame(trials.results)
params_df = json_normalize(results_df["params"])
results_df = pd.concat([results_df.drop("params", axis=1), params_df],
                       axis=1)
results_df["iteration"] = np.arange(len(results_df)) + 1
results_df.sort_values("loss")

"""7. Plot the prior distribution of `colsample_bytree` and the one used during the HPO:"""

cbt_samples = draw_samples(search_space["colsample_bytree"])

fig, ax = plt.subplots(1, 2, figsize = (16, 8))

sns.kdeplot(cbt_samples,
            label="Sampling Distribution",
            ax=ax[0])
sns.kdeplot(results_df["colsample_bytree"],
            label="Bayesian Optimization",
            ax=ax[0])
ax[0].set(title="Distribution of colsample_bytree",
          xlabel="Value",
          ylabel="Density")
ax[0].legend()

sns.regplot("iteration", "colsample_bytree",
            data=results_df, ax=ax[1])
ax[1].set(title="colsample_bytree over Iterations",
          xlabel="Iteration",
          ylabel="Value")

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_24", dpi=200)

"""8. Plot the distribution of `n_estimators`:"""

(
    results_df["n_estimators"]
    .value_counts()
    .plot(kind="bar",
          title="Distribution of # of Estimators")
)

plt.tight_layout()
sns.despine()

"""9. Plot the evolution of the observed losses over iterations:"""

best_ind = results_df["loss"].argmin()

fig, ax = plt.subplots()
ax.plot(results_df["iteration"], results_df["loss"], "o")
ax.plot(results_df["iteration"].iloc[best_ind],
        results_df["loss"].iloc[best_ind],
        "k*", markersize=16)
ax.set(title="Evolution of loss over iterations",
       xlabel="Iteration",
       ylabel="Loss")
plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_25", dpi=200)

"""## 14.6 Investigating feature importance

### Getting Ready

1. Import the libraries:
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from chapter_14_utils import performance_evaluation_report

"""2. Load data, preprocess it, define the model (and its hyperparameters) and fit it:"""

df = pd.read_csv("../Datasets/credit_card_default.csv", na_values="")

X = df.copy()
y = X.pop("default_payment_next_month")

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    stratify=y,
                                                    random_state=42)

num_features = X_train.select_dtypes(include="number").columns.to_list()
cat_features = X_train.select_dtypes(include="object").columns.to_list()

num_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

cat_list = [list(X_train[col].dropna().unique()) for col in cat_features]

cat_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(categories=cat_list, sparse=False,
                             handle_unknown="error", drop="first"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("numerical", num_pipeline, num_features),
        ("categorical", cat_pipeline, cat_features)
    ],
    remainder="drop"
)

rf_pipeline = Pipeline(
    steps=[("preprocessor", preprocessor),
           ("classifier", RandomForestClassifier(random_state=42))]
)

# optional step
# set the hyperparameters to the one obtained from tuning in Recipe 14.1
best_params = {
    "n_estimators": 300,
    "min_samples_split": 2,
    "min_samples_leaf": 7,
    "max_features": None,
    "max_depth": 8,
    "bootstrap": False
}
rf_pipeline["classifier"].set_params(**best_params)

rf_pipeline.fit(X_train, y_train)

LABELS = ["No Default", "Default"]
rf_perf = performance_evaluation_report(rf_pipeline, X_test,
                                        y_test, labels=LABELS,
                                        show_plot=True,
                                        show_pr_curve=True)

"""3. Sanity check for the recall score (compared to results in Recipe 14.1):"""

print(f"Recall: {rf_perf['recall']:.4f}")

"""### How to do it...

1. Import the libraries:
"""

import numpy as np
import pandas as pd
from sklearn.inspection import permutation_importance
from sklearn.metrics import recall_score
from sklearn.base import clone

"""2. Extract the classifier and preprocessor from the fitted pipeline:"""

rf_classifier = rf_pipeline.named_steps["classifier"]
preprocessor = rf_pipeline.named_steps["preprocessor"]

"""3. Recover feature names from the preprocessing transformer and transform the training/test sets:"""

feat_names = list(preprocessor.get_feature_names_out())
feat_names = [name.replace("numerical__", "").replace("categorical__", "") for name in feat_names]

X_train_preprocessed = pd.DataFrame(
    preprocessor.transform(X_train),
    columns=feat_names
)

X_test_preprocessed = pd.DataFrame(
    preprocessor.transform(X_test),
    columns=feat_names
)

"""4. Extract the MDI feature importance and calculate the cumulative importance:"""

rf_feat_imp = pd.DataFrame(rf_classifier.feature_importances_,
                           index=feat_names,
                           columns=["mdi"])

rf_feat_imp["mdi_cumul"] = np.cumsum(
    rf_feat_imp
    .sort_values("mdi", ascending=False)
    .loc[:, "mdi"]
).loc[feat_names]

rf_feat_imp.head()

"""5. Define a function for plotting top X features in terms of their importance:"""

def plot_most_important_features(feat_imp, title,
                                 n_features=10,
                                 bottom=False):
    """
    Function for plotting the top/bottom x features in terms of their importance.

    Parameters
    ----------
    feat_imp : pd.Series
        A pd.Series with calculated feature importances
    title : str
        A string representing the title of calculating the importances.
    n_features : int
        Number of top/bottom features to plot
    bottom : boolean
        Indicates if the plot should contain the bottom feature importances.

    Returns
    -------
    ax : matplotlib.axes._subplots.AxesSubplot
        Ax cointaining the plot
    """

    if bottom:
        indicator = "Bottom"
        feat_imp = feat_imp.sort_values(ascending=True)
    else:
        indicator = "Top"
        feat_imp = feat_imp.sort_values(ascending=False)

    ax = feat_imp.head(n_features).plot.barh()
    ax.invert_yaxis()
    ax.set(title=f"{title} ({indicator} {n_features})",
           xlabel="Importance",
           ylabel="Feature")

    return ax

plot_most_important_features(rf_feat_imp["mdi"],
                             title="MDI Importance")

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_26", dpi=200)

"""6. Plot the cumulative importance of the features:"""

x_values = range(len(feat_names))

fig, ax = plt.subplots()
ax.plot(x_values, rf_feat_imp["mdi_cumul"].sort_values(), "b-")
ax.hlines(y=0.95, xmin=0, xmax=len(x_values),
          color="g", linestyles="dashed")
ax.set(title="Cumulative MDI Importance",
       xlabel="# Features",
       ylabel="Importance")

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_27", dpi=200)

top_10_importance = rf_feat_imp.sort_values("mdi", ascending=False).head(10)["mdi"].sum()
importance_95_perc = rf_feat_imp[rf_feat_imp["mdi_cumul"] <= 0.95].shape[0]

print(f"Top 10 features account for {100 * top_10_importance:.2f}% of the total importance.")
print(f"Top {importance_95_perc} features account for 95% of importance.")

"""7. Calculate and plot permutation importance using the training set:"""

perm_result_train = permutation_importance(
    rf_classifier, X_train_preprocessed, y_train,
    n_repeats=25, scoring="recall",
    random_state=42, n_jobs=-1
)

rf_feat_imp["perm_imp_train"] = (
    perm_result_train["importances_mean"]
)

perm_result_train.keys()

plot_most_important_features(
    rf_feat_imp["perm_imp_train"],
    title="Permutation importance - training set"
)

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_28", dpi=200)

"""8. Calculate and plot permutation importance using the test set:"""

perm_result_test = permutation_importance(
    rf_classifier, X_test_preprocessed, y_test,
    n_repeats=25, scoring="recall",
    random_state=42, n_jobs=-1
)

rf_feat_imp["perm_imp_test"] = (
    perm_result_test["importances_mean"]
)

plot_most_important_features(
    rf_feat_imp["perm_imp_test"],
    title="Permutation importance - test set"
)

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_29", dpi=200)

"""9. Define a function for calculating the drop-column feature importance:"""

def drop_col_feat_imp(model, X, y, metric, random_state=42):
    '''
    Function for calculating the drop column feature importance.

    Parameters
    ----------
    model : scikit-learn's model
        Object representing the estimator with selected hyperparameters.
    X : pd.DataFrame
        Features for training the model
    y : pd.Series
        The target
    metric : a sklearn metric
        Metric such as accuracy_score, precision_score or recall_score
    random_state : int
        Random state for reproducibility

    Returns
    -------
    importances : list
        List containing the calculated feature importances in the order of appearing in X

    '''

    model_clone = clone(model)
    model_clone.random_state = random_state
    model_clone.fit(X, y)
    benchmark_score = metric(y, model_clone.predict(X))

    importances = []

    for ind, col in enumerate(X.columns):
        print(f"Dropping {col} ({ind+1}/{len(X.columns)})")
        model_clone = clone(model)
        model_clone.random_state = random_state
        model_clone.fit(X.drop(col, axis = 1), y)
        drop_col_score = metric(
            y, model_clone.predict(X.drop(col, axis = 1))
        )
        importances.append(benchmark_score - drop_col_score)

    return importances

"""10. Calculate and plot the drop-column feature importance:"""

rf_feat_imp["drop_column_imp"] = drop_col_feat_imp(
    rf_classifier.set_params(**{"n_jobs": -1}),
    X_train_preprocessed,
    y_train,
    metric = recall_score,
    random_state = 42
)

plot_most_important_features(
    rf_feat_imp["drop_column_imp"],
    title="Drop column importance"
)

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_30", dpi=200)

plot_most_important_features(
    rf_feat_imp["drop_column_imp"],
    title="Drop column importance",
    bottom=True
)

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_31", dpi=200)

"""### There's more"""

sorted_imp_ind = perm_result_train["importances_mean"].argsort()[-10:]

importances = pd.DataFrame(
    perm_result_train["importances"][sorted_imp_ind].T,
    columns=X_train_preprocessed.columns[sorted_imp_ind],
)

ax = importances.plot.box(vert=False, whis=10)
ax.set_title("Permutation importance (training set)")
ax.set_xlabel("Decrease in recall score")

plt.tight_layout()
sns.despine()

"""## 14.7 Exploring feature selection techniques

### Getting ready
"""

import pandas as pd
from sklearn.model_selection import train_test_split

RANDOM_STATE = 42

df = pd.read_csv("../Datasets/credit_card_fraud.csv")

X = df.copy().drop(columns=["Time"])
y = X.pop("Class")

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=RANDOM_STATE
)

"""### How to do it...

1. Import the libraries:
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score
from sklearn.feature_selection import (RFE, RFECV,
                                       SelectKBest,
                                       SelectFromModel,
                                       mutual_info_classif)
from sklearn.model_selection import StratifiedKFold

"""2. Train the benchmark model:"""

rf = RandomForestClassifier(random_state=RANDOM_STATE,
                            n_jobs=-1)
rf.fit(X_train, y_train)

recall_train = recall_score(y_train, rf.predict(X_train))
recall_test = recall_score(y_test, rf.predict(X_test))
print(f"Recall score training: {recall_train:.4f}")
print(f"Recall score test: {recall_test:.4f}")

"""3. Select the best features using Mutual Information:"""

scores = []
n_features_list = list(range(2, len(X_train.columns)+1))

for n_feat in n_features_list:
    print(f"Keeping {n_feat} most important features")
    mi_selector = SelectKBest(mutual_info_classif, k=n_feat)
    X_train_new = mi_selector.fit_transform(X_train, y_train)
    X_test_new = mi_selector.transform(X_test)

    rf.fit(X_train_new, y_train)
    recall_scores = [
        recall_score(y_train, rf.predict(X_train_new)),
        recall_score(y_test, rf.predict(X_test_new))
    ]
    scores.append(recall_scores)

mi_scores_df = pd.DataFrame(
    scores,
    columns=["train_score", "test_score"],
    index=n_features_list
)

(
    mi_scores_df["test_score"]
    .plot(kind="bar",
          title="Feature selection using Mutual Information",
          xlabel="# of features",
          ylabel="Recall (test set)")
)

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_32", dpi=200)

mi_scores_df["test_score"].sort_values(ascending=False).head(5)

mi_selector = SelectKBest(mutual_info_classif, k=8)
mi_selector.fit(X_train, y_train)
print(f"Most importance features according to MI: {mi_selector.get_feature_names_out()}")

"""4. Select the best features using MDI feature importance, retrain the model and evaluate its performance:"""

# fit the selector
rf_selector = SelectFromModel(rf)
rf_selector.fit(X_train, y_train)

# evaluate the model
mdi_features = X_train.columns[rf_selector.get_support()]
rf.fit(X_train[mdi_features], y_train)
recall_train = recall_score(
    y_train, rf.predict(X_train[mdi_features])
)
recall_test = recall_score(y_test, rf.predict(X_test[mdi_features]))
print(f"Recall score training: {recall_train:.4f}")
print(f"Recall score test: {recall_test:.4f}")

print(f"MDI importance threshold: {rf_selector.threshold_:.4f}")
print(f"Most importance features according to MDI: {rf_selector.get_feature_names_out()}")

# train the simple RF model
rf = RandomForestClassifier(random_state=RANDOM_STATE, n_jobs=-1)
rf.fit(X_train, y_train)

# recover the feature importances, sort by importance descending
mdi_imp = pd.Series(
    rf.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

# define a list for storing the scores
scores = []

# iterate increasing the number of retained features by 1 with each loop
n_features_list = range(2, len(mdi_imp)+1)
for n_feat in n_features_list:

    print(f"Keeping {n_feat} most important features")
    selected_features = mdi_imp.iloc[:n_feat].index.to_list()

    rf.fit(X_train[selected_features], y_train)
    recall_scores = [
        recall_score(y_train, rf.predict(X_train[selected_features])),
        recall_score(y_test, rf.predict(X_test[selected_features]))
    ]
    scores.append(recall_scores)

mdi_scores_df = pd.DataFrame(
    scores,
    columns=["train_score", "test_score"],
    index=n_features_list
)

mdi_scores_df.sort_values("test_score", ascending=False).head()

(
    mdi_scores_df["test_score"]
    .plot(kind="bar",
          title="Feature selection using MDI",
          xlabel="# of features",
          ylabel="Recall (test set)")
)

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_33", dpi=200)

"""5. Select the best 10 features using Recursive Feature Elimination:"""

rfe = RFE(estimator=rf, n_features_to_select=10, verbose=1)
rfe.fit(X_train, y_train)

rfe_features = rfe.get_feature_names_out()
rf.fit(X_train[rfe_features], y_train)
recall_train = recall_score(y_train, rf.predict(X_train[rfe_features]))
recall_test = recall_score(y_test, rf.predict(X_test[rfe_features]))
print(f"Most importance features according to RFE: {rfe_features}")
print(f"Recall score training: {recall_train:.4f}")
print(f"Recall score test: {recall_test:.4f}")

"""6. Select the best features using Recursive Feature Elimination with cross-validation:"""

k_fold = StratifiedKFold(5, shuffle=True, random_state=42)

rfe_cv = RFECV(estimator=rf, step=1,
               cv=k_fold,
               min_features_to_select=5,
               scoring="recall",
               verbose=1, n_jobs=-1)
rfe_cv.fit(X_train, y_train)

rfecv_features = rfe_cv.get_feature_names_out()
rf.fit(X_train[rfecv_features], y_train)
recall_train = recall_score(y_train, rf.predict(X_train[rfecv_features]))
recall_test = recall_score(y_test, rf.predict(X_test[rfecv_features]))
print(f"Most importance features according to RFECV: {rfecv_features}")
print(f"Recall score training: {recall_train:.4f}")
print(f"Recall score test: {recall_test:.4f}")

# we added 5 as we set min_features_to_select to 5 while calling RFECV
cv_results_df = pd.DataFrame(rfe_cv.cv_results_)
cv_results_df.index += 5
cv_results_df

(
    cv_results_df["mean_test_score"]
    .plot(title="Average CV score over iterations",
          xlabel="# of features retained",
          ylabel="Avg. recall")
)

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_34", dpi=200)

import numpy as np
np.ceil((29 - 5) / 1) + 1

# feature importances derived from the last fitted model
rfe_cv.estimator_.feature_importances_

"""### There's more

#### Combining feature selection and hyperparameter tuning
"""

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

pipeline = Pipeline(
   [
    ("selector", SelectKBest(mutual_info_classif)),
    ("model", rf)
   ]
)

param_grid = {
   "selector__k": [5, 10, 20, 29],
   "model__n_estimators": [10, 50, 100, 200]
}

gs = GridSearchCV(
   estimator=pipeline,
   param_grid=param_grid,
   n_jobs=-1,
   scoring="recall",
   cv=k_fold,
   verbose=1
)

gs.fit(X_train, y_train)
print(f"Best hyperparameters: {gs.best_params_}")

"""## 14.8 Exploring the Explainable AI (XAI) techniques

### Getting ready
"""

import pandas as pd
from sklearn.model_selection import train_test_split

RANDOM_STATE = 42

df = pd.read_csv("../Datasets/credit_card_fraud.csv")

X = df.copy().drop(columns=["Time"])
y = X.pop("Class")

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=RANDOM_STATE
)

"""### How to do it...

1. Import the libraries:
"""

from xgboost import XGBClassifier
from sklearn.metrics import recall_score
from sklearn.inspection import (partial_dependence,
                                PartialDependenceDisplay)
import shap

"""2. Train the ML model:"""

xgb = XGBClassifier(random_state=RANDOM_STATE,
                    n_jobs=-1)
xgb.fit(X_train, y_train)

recall_train = recall_score(y_train, xgb.predict(X_train))
recall_test = recall_score(y_test, xgb.predict(X_test))
print(f"Recall score training: {recall_train:.4f}")
print(f"Recall score test: {recall_test:.4f}")

"""3. Plot the ICE curves:"""

PartialDependenceDisplay.from_estimator(
    xgb, X_train, features=["V4"],
    kind="individual",
    subsample=5000,
    line_kw={"linewidth": 2},
    random_state=RANDOM_STATE
)
plt.title("ICE curves of V4")

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_35", dpi=200)

PartialDependenceDisplay.from_estimator(
    xgb, X_train, features=["V4"],
    kind="individual",
    subsample=5000,
    line_kw={"linewidth": 2},
    percentiles = (0,1),
    random_state=RANDOM_STATE
)
# plt.title("ICE curves of V4 - full range of the feature")

"""4. Plot the centered ICE curves:"""

PartialDependenceDisplay.from_estimator(
    xgb, X_train, features=["V4"],
    kind="individual",
    subsample=5000,
    centered=True,
    line_kw={"linewidth": 2},
    random_state=RANDOM_STATE
)
plt.title("Centered ICE curves of V4")

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_36", dpi=200)

"""5. Generate the Partial Dependence Plot:"""

PartialDependenceDisplay.from_estimator(
    xgb, X_train,
    features=["V4"],
    random_state=RANDOM_STATE
)
plt.title("Partial Dependence Plot of V4")

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_37", dpi=200)

PartialDependenceDisplay.from_estimator(xgb, X_train, features=["V4"],
                                        random_state=RANDOM_STATE, centered=True)
plt.title("Centered Partial Dependence Plot of V4");

PartialDependenceDisplay.from_estimator(
    xgb, X_train, features=["V4"],
    kind="both",
    subsample=5000,
    ice_lines_kw={"linewidth": 2},
    pd_line_kw={"color": "red"},
    random_state=RANDOM_STATE
)
# plt.ylim(0, 0.05)
plt.title("Partial Dependence Plot of V4, together with ICE curves")

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_38", dpi=200)

"""6. Generate the individual PDPs of two features and a joint one:"""

fig, ax = plt.subplots(figsize=(20, 8))

PartialDependenceDisplay.from_estimator(
    xgb,
    X_train.sample(20000, random_state=RANDOM_STATE),
    features=["V4", "V8", ("V4", "V8")],
    centered=True,
    ax=ax
)
ax.set_title("Centered Partial Dependence Plots of V4 and V8")

plt.tight_layout()
sns.despine()
# plt.savefig("images/figure_14_39", dpi=200)

"""7. Instantiate an explainer and calculate the SHAP values:"""

explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X)
explainer_x = explainer(X)

shap_values.shape

# it might be required to run this command before creating the plots
shap.initjs()

"""8. Generate the SHAP summary plot:"""

shap.summary_plot(shap_values, X);

shap.summary_plot(shap_values, X, plot_type="bar");

shap.plots.bar(explainer_x)

"""9. Locate an observation belonging to the positive and negative class:

Explaining single prediction

Let’s start small and simple. With SHAP, we can generate explanations for a single prediction. The SHAP plot shows features that contribute to pushing the output from the base value (average model output) to the actual predicted value.

Red color indicates features that are pushing the prediction higher, and blue color indicates just the opposite.
"""

negative_ind = y[y == 0].index[0]
positive_ind = y[y == 1].index[0]

"""10. Explain those observations:"""

shap.force_plot(
    explainer.expected_value,
    shap_values[negative_ind, :],
    X.iloc[negative_ind, :]
)

explainer.expected_value

shap.force_plot(
    explainer.expected_value,
    shap_values[positive_ind, :],
    X.iloc[positive_ind, :]
)

"""11. Create a waterfall plot for the positive observation:"""

shap.plots.waterfall(explainer(X)[positive_ind])
# shap.plots.waterfall(explainer(X)[positive_ind], max_display=30)

"""12. Create a dependence plot of the `V4` feature:"""

shap.dependence_plot("V4", shap_values, X)

"""### There's more"""

dependence_dict = partial_dependence(rf, X_train, "V17", kind="both")
dependence_dict.keys()

dependence_dict["average"]

dependence_dict["individual"].shape

dependence_dict["values"]