# -*- coding: utf-8 -*-
"""chapter_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n3sATDtVEAQZ1LTMrsvg7eZmbMTG8ey

Please run those two cells before running the Notebook!

As those plotting settings are standard throughout the book, we do not show them in the book every time we plot something.
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
# %config InlineBackend.figure_format = "retina"

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

# feel free to modify, for example, change the context to "notebook"
sns.set_theme(context="talk", style="whitegrid",
              palette="colorblind", color_codes=True,
              rc={"figure.figsize": [12, 8]})

"""# Chapter 2 - Data Preprocessing

## 2.1 Converting prices to returns

### How to do it...

1. Import the libraries:
"""

import pandas as pd
import numpy as np
import yfinance as yf

"""2. Download the data and keep the adjusted close prices only:"""

df = yf.download("AAPL",
                 start="2010-01-01",
                 end="2020-12-31",
                 progress=False)

df = df.loc[:, ["Adj Close"]]

"""3. Convert adjusted close prices to simple and log returns:"""

df["simple_rtn"] = df["Adj Close"].pct_change()
df["log_rtn"] = np.log(df["Adj Close"]/df["Adj Close"].shift(1))

"""4. Inspect the output:"""

df.head()

"""## 2.2 Adjusting the returns for inflation

### How to do it...

0. Recreating the steps from the previous recipe:
"""

import yfinance as yf

df = yf.download("AAPL",
                 start="2010-01-01",
                 end="2020-12-31",
                 progress=False)

df = df.loc[:, ["Adj Close"]]

"""1. Import libraries and authenticate:"""

import pandas as pd
import nasdaqdatalink

nasdaqdatalink.ApiConfig.api_key = "YOUR_KEY_HERE"

"""2. Resample daily prices to monthly:"""

df = df.resample("M").last()
df

"""3. Download inflation data from Nasdaq Data Link:"""

df_cpi = (
    nasdaqdatalink.get(dataset="RATEINF/CPI_USA",
                       start_date="2009-12-01",
                       end_date="2020-12-31")
    .rename(columns={"Value": "cpi"})
)

df_cpi

"""4. Join inflation data to prices:"""

df = df.join(df_cpi, how="left")

"""5. Calculate simple returns and inflation rate:"""

df["simple_rtn"] = df["Adj Close"].pct_change()
df["inflation_rate"] = df["cpi"].pct_change()

"""6. Adjust the returns for inflation:"""

df["real_rtn"] = (
    (df["simple_rtn"] + 1) / (df["inflation_rate"] + 1) - 1
)
df.head()

"""### There's more

1. Import the library:
"""

import cpi

# in the case of seeing the `StaleDataWarning: CPI data is out of date`
cpi.update()

"""2. Obtain the default CPI series:"""

cpi_series = cpi.series.get()
cpi_series

print(cpi_series)

"""3. Convert the object into a `pandas` DataFrame:"""

df_cpi_2 = cpi_series.to_dataframe()

"""4. Filter the DataFrame and view the top 12 observations:"""

df_cpi_2.query("period_type == 'monthly' and year >= 2010") \
        .loc[:, ["date", "value"]] \
        .set_index("date") \
        .head(12)

"""## 2.3 Changing the frequency of time series data

### How to do it...

0. Obtain the log returns in case of starting in this recipe:
"""

import pandas as pd
import yfinance as yf
import numpy as np

# download data
df = yf.download("AAPL",
                 start="2000-01-01",
                 end="2010-12-31",
                 auto_adjust=False,
                 progress=False)

# keep only the adjusted close price
df = df.loc[:, ["Adj Close"]] \
       .rename(columns={"Adj Close": "adj_close"})

# calculate simple returns
df["log_rtn"] = np.log(df["adj_close"]/df["adj_close"].shift(1))

# remove redundant data
df = df.drop("adj_close", axis=1) \
       .dropna(axis=0)

df.head()

"""1. Import the libraries:"""

import pandas as pd
import numpy as np

"""2. Define the function for calculating the realized volatility:"""

def realized_volatility(x):
    return np.sqrt(np.sum(x**2))

"""3. Calculate monthly realized volatility:"""

df_rv = (
    df.groupby(pd.Grouper(freq="M"))
    .apply(realized_volatility)
    .rename(columns={"log_rtn": "rv"})
)

"""4. Annualize the values:"""

df_rv.rv = df_rv["rv"] * np.sqrt(12)

"""5. Plot the results:"""

fig, ax = plt.subplots(2, 1, sharex=True)
ax[0].plot(df)
ax[0].set_title("Apple's log returns (2000-2012)")
ax[1].plot(df_rv)
ax[1].set_title("Annualized realized volatility")

sns.despine()
plt.tight_layout()
# plt.savefig('images/figure_2_5', dpi=200)

"""## 2.4 Different ways of imputing missing data

### How to do it...

1. Import the libraries:
"""

import pandas as pd
import numpy as np
import nasdaqdatalink

"""2. Download the inflation data from Nasdaq Data Link:"""

nasdaqdatalink.ApiConfig.api_key = "YOUR_KEY_HERE"

df = (
    nasdaqdatalink.get(dataset="RATEINF/CPI_USA",
                       start_date="2015-01-01",
                       end_date="2020-12-31")
    .rename(columns={"Value": "cpi"})
)

"""3. Introduce 5 missing values at random:"""

np.random.seed(42)
rand_indices = np.random.choice(df.index, 5, replace=False)

df["cpi_missing"] = df.loc[:, "cpi"]
df.loc[rand_indices, "cpi_missing"] = np.nan
df.head()

"""4. Fill the missing values using different methods:"""

for method in ["bfill", "ffill"]:
    df[f"method_{method}"] = (
        df[["cpi_missing"]].fillna(method=method)
    )

"""5. Inspect the results by displaying the rows in which we created the missing values:"""

df.loc[rand_indices].sort_index()

"""6. Plot the results for years 2015-2016:"""

df.loc[:"2017-01-01"] \
  .drop(columns=["cpi_missing"]) \
  .plot(title="Different ways of filling missing values");

sns.despine()
plt.tight_layout()
# plt.savefig('images/figure_2_8', dpi=200)

"""### There's more

1. Use linear interpolation to fill the missing values:
"""

df["method_interpolate"] = df[["cpi_missing"]].interpolate()

"""2. Inspect the results:"""

df.loc[rand_indices].sort_index()

"""3. Plot the results:"""

df.loc[:"2017-01-01"] \
  .drop(columns=["cpi_missing"]) \
  .plot(title="Different ways of filling missing values");

sns.despine()
plt.tight_layout()
# plt.savefig('images/figure_2_10', dpi=200)

"""## 2.5 Converting currencies

### How to do it...

1. Import the libraries:
"""

import pandas as pd
import yfinance as yf
from forex_python.converter import CurrencyRates

"""2. Download Apple's OHLC prices from January 2020:"""

df = yf.download("AAPL",
                 start="2020-01-01",
                 end="2020-01-31",
                 progress=False)
df = df.drop(columns=["Adj Close", "Volume"])

"""3. Instantiate the `CurrencyRates` object:"""

c = CurrencyRates()

"""4. Download the USD/EUR rate for each required date:"""

df["usd_eur"] = [c.get_rate("USD", "EUR", date) for date in df.index]

"""5. Convert the prices in USD to EUR:"""

for column in df.columns[:-1]:
    df[f"{column}_EUR"] = df[column] * df["usd_eur"]
df.head().round(3)

"""### There's more

1. Get the USD exchange rates to 31 available currencies:
"""

usd_rates = c.get_rates("USD")
usd_rates

len(usd_rates)

"""2. Download the USD/EUR exchange rate from Yahoo Finance:"""

df = yf.download("USDEUR=X",
                 start="2000-01-01",
                 end="2010-12-31",
                 progress=False)
df.head()

"""## 2.6 Different ways of aggregating trade data

### How to do it...

1. Import the libraries:
"""

from binance.spot import Spot as Client
import pandas as pd
import numpy as np

"""2. Instantiate the Binance client and download the last 500 `BTCEUR` trades:"""

spot_client = Client(base_url="https://api3.binance.com")
r = spot_client.trades("BTCEUR")

"""3. Process the downloaded trades into a `pandas` DataFrame:"""

df = (
    pd.DataFrame(r)
    .drop(columns=["isBuyerMaker", "isBestMatch"])
)
df["time"] = pd.to_datetime(df["time"], unit="ms")

for column in ["price", "qty", "quoteQty"]:
    df[column] = pd.to_numeric(df[column])
df

"""4. Define a function aggregating the raw trades information:"""

def get_bars(df, add_time=False):
    """[summary]

    Args:
        df ([type]): [description]

    Returns:
        [type]: [description]
    """
    ohlc = df["price"].ohlc()
    vwap = (
        df.apply(lambda x: np.average(x["price"], weights=x["qty"]))
        .to_frame("vwap")
    )
    vol = df["qty"].sum().to_frame("vol")
    cnt = df["qty"].size().to_frame("cnt")

    if add_time:
        time = df["time"].last().to_frame("time")
        res = pd.concat([time, ohlc, vwap, vol, cnt], axis=1)
    else:
        res = pd.concat([ohlc, vwap, vol, cnt], axis=1)
    return res

"""5. Get time bars:"""

df_grouped_time = df.groupby(pd.Grouper(key="time", freq="1Min"))
time_bars = get_bars(df_grouped_time)
time_bars

"""6. Get tick bars:"""

bar_size = 50
df["tick_group"] = (
    pd.Series(list(range(len(df))))
    .div(bar_size)
    .apply(np.floor)
    .astype(int)
    .values
)
df_grouped_ticks = df.groupby("tick_group")
tick_bars = get_bars(df_grouped_ticks, add_time=True)
tick_bars

"""7. Get volume bars:"""

bar_size = 1
df["cum_qty"] = df["qty"].cumsum()
df["vol_group"] = (
    df["cum_qty"]
    .div(bar_size)
    .apply(np.floor)
    .astype(int)
    .values
)
df_grouped_ticks = df.groupby("vol_group")
volume_bars = get_bars(df_grouped_ticks, add_time=True)
volume_bars

"""8. Get dollar bars:"""

bar_size = 50000
df["cum_value"] = df["quoteQty"].cumsum()
df["value_group"] = (
    df["cum_value"]
    .div(bar_size)
    .apply(np.floor)
    .astype(int)
    .values
)
df_grouped_ticks = df.groupby("value_group")
dollar_bars = get_bars(df_grouped_ticks, add_time=True)
dollar_bars