# -*- coding: utf-8 -*-
"""chapter_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_diRNQIJVFy_xe1hIbHpmjpQxxK81yD

Please run those two cells before running the Notebook!

As those plotting settings are standard throughout the book, we do not show them in the book every time we plot something.
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
# %config InlineBackend.figure_format = "retina"

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
from pandas.core.common import SettingWithCopyWarning
warnings.simplefilter(action="ignore", category=FutureWarning)
warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

# feel free to modify, for example, change the context to "notebook"
sns.set_theme(context="talk", style="whitegrid",
              palette="colorblind", color_codes=True,
              rc={"figure.figsize": [12, 8]})

"""# Chapter 5 - Technical Analysis and Building Interactive Dashboards

## 5.1 Calculating the most popular technical indicators

### How to do it...

1. Import the libraries:
"""

import pandas as pd
import yfinance as yf
import talib

"""2. Download IBM's stock prices from 2020:"""

df = yf.download("IBM",
                 start="2020-01-01",
                 end="2020-12-31",
                 progress=False,
                 auto_adjust=True)
df

"""3. Calculate and plot the Simple Moving Average:"""

df["sma_20"] = talib.SMA(df["Close"], timeperiod=20)
(
    df[["Close", "sma_20"]]
    .plot(title="20-day Simple Moving Average (SMA)")
)

sns.despine()
plt.tight_layout()
# plt.savefig("images/figure_5_1", dpi=200)

"""4. Calculate and plot the Bollinger bands:"""

df["bb_up"], df["bb_mid"], df["bb_low"] = talib.BBANDS(df["Close"])

fig, ax = plt.subplots()

(
    df.loc[:, ["Close", "bb_up", "bb_mid", "bb_low"]]
    .plot(ax=ax, title="Bollinger Bands")
)

ax.fill_between(df.index, df["bb_low"], df["bb_up"],
                color="gray",
                alpha=.4)

sns.despine()
plt.tight_layout()
# plt.savefig("images/figure_5_2", dpi=200)

"""5. Calculate and plot the RSI:"""

df["rsi"] = talib.RSI(df["Close"])

fig, ax = plt.subplots()
df["rsi"].plot(ax=ax,
               title="Relative Strength Index (RSI)")
ax.hlines(y=30,
          xmin=df.index.min(),
          xmax=df.index.max(),
          color="red")
ax.hlines(y=70,
          xmin=df.index.min(),
          xmax=df.index.max(),
          color="red")

sns.despine()
plt.tight_layout()
# plt.savefig("images/figure_5_3", dpi=200)

"""6. Calculate and plot the MACD:"""

df["macd"], df["macdsignal"], df["macdhist"] = talib.MACD(
    df["Close"], fastperiod=12, slowperiod=26, signalperiod=9
)

with sns.plotting_context("notebook"):
    fig, ax = plt.subplots(2, 1, sharex=True)

    (
        df[["macd", "macdsignal"]].
        plot(ax=ax[0],
             title="Moving Average Convergence Divergence (MACD)")
    )
    ax[1].bar(df.index, df["macdhist"].values, label="macd_hist")
    ax[1].legend()

    sns.despine()
    plt.tight_layout()
    # plt.savefig("images/figure_5_4", dpi=200)

"""### There's more

1. Import the libraries:
"""

from ta import add_all_ta_features

"""2. Discard the previously calculated indicators and keep only the required columns:"""

df = df[["Open", "High", "Low", "Close", "Volume"]].copy()

"""3. Calculate all the technical indicators available in the `ta` library:"""

df = add_all_ta_features(df, open="Open", high="High",
                         low="Low", close="Close",
                         volume="Volume")

df.shape

df.columns

"""## 5.2 Downloading the technical indicators

### How to do it...

1. Import the libraries:
"""

from alpha_vantage.techindicators import TechIndicators

"""2. Instantiate the `TechIndicators` class and authenticate:"""

ta_api = TechIndicators(key="YOUR_KEY_HERE",
                        output_format="pandas")

"""3. Download the RSI for IBM's stock:"""

rsi_df, rsi_meta = ta_api.get_rsi(symbol="IBM",
                                  time_period=14)

"""4. Plot the downloaded RSI:"""

fig, ax = plt.subplots()
rsi_df.plot(ax=ax,
            title="RSI downloaded from Alpha Vantage")
ax.hlines(y=30,
          xmin=rsi_df.index.min(),
          xmax=rsi_df.index.max(),
          color="red")
ax.hlines(y=70,
          xmin=rsi_df.index.min(),
          xmax=rsi_df.index.max(),
          color="red")

sns.despine()
plt.tight_layout()
# plt.savefig("images/figure_5_5", dpi=200)

rsi_df

"""5. Explore the metadata object:"""

rsi_meta

"""### There's more

1. Import the libraries:
"""

import intrinio_sdk as intrinio
import pandas as pd

"""2. Authenticate using the personal API key and select the API:"""

intrinio.ApiClient().set_api_key("YOUR_KEY_HERE")
security_api = intrinio.SecurityApi()

"""3. Request the MACD for IBM's stock from 2020:"""

r = security_api.get_security_price_technicals_macd(
    identifier="IBM",
    fast_period=12,
    slow_period=26,
    signal_period=9,
    price_key="close",
    start_date="2020-01-01",
    end_date="2020-12-31",
    page_size=500
)

"""4. Convert the request's output into a `pandas` DataFrame:"""

macd_df = (
    pd.DataFrame(r.technicals_dict)
    .sort_values("date_time")
    .set_index("date_time")
)
macd_df.index = pd.to_datetime(macd_df.index).date
macd_df

"""5. Plot the MACD:"""

with sns.plotting_context("notebook"):

    fig, ax = plt.subplots(2, 1, sharex=True)

    (
        macd_df[["macd_line", "signal_line"]]
        .plot(ax=ax[0],
              title="MACD downloaded from Intrinio")
    )
    ax[1].bar(df.index, macd_df["macd_histogram"].values,
              label="macd_hist")
    ax[1].legend()

    sns.despine()
    plt.tight_layout()
    # plt.savefig("images/figure_5_6", dpi=200)

"""## 5.3 Recognizing candlestick patterns

### How to do it...

1. Import the libraries:
"""

import pandas as pd
import yfinance as yf
import talib
import mplfinance as mpf

"""2. Download Bitcoin's hourly prices from the last 3 months:"""

df = yf.download("BTC-USD",
                 period="9mo",
                 interval="1h",
                 progress=False)
df

"""3. Identify the "Three Line Strike" pattern:"""

df["3_line_strike"] = talib.CDL3LINESTRIKE(
    df["Open"], df["High"], df["Low"], df["Close"]
)

"""4. Locate and plot the bearish pattern:"""

df[df["3_line_strike"] == -100].head().round(2)

mpf.plot(df["2021-07-16 05:00:00":"2021-07-16 16:00:00"],
         type="candle")

"""5. Locate and plot the bullish pattern:"""

df[df["3_line_strike"] == 100].head().round(2)

mpf.plot(df["2021-07-10 10:00:00":"2021-07-10 23:00:00"],
         type="candle")

"""### There's more

1. Get all available pattern names:
"""

candle_names = talib.get_function_groups()["Pattern Recognition"]

"""2. Iterate over the list of patterns and try identifying them all:"""

for candle in candle_names:
    df[candle] = getattr(talib, candle)(df["Open"], df["High"],
                                        df["Low"], df["Close"])

"""3. Inspect the summary statistics of the patterns:"""

with pd.option_context("display.max_rows", len(candle_names)):
    display(df[candle_names].describe().transpose().round(2))

"""4. Locate and plot the "Evening Star" pattern:"""

df[df["CDLEVENINGSTAR"]  == -100].head()

mpf.plot(df["2021-09-21 12:00:00":"2021-09-22 03:00:00"], type="candle")