# -*- coding: utf-8 -*-
"""chapter_11_bonus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EZ8U-HoxgSSSR-m8cgZxxJlU4fOkM3J0

Please run those two cells before running the Notebook!

As those plotting settings are standard throughout the book, we do not show them in the book every time we plot something.
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
# %config InlineBackend.figure_format = "retina"

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
from pandas.core.common import SettingWithCopyWarning
warnings.simplefilter(action="ignore", category=FutureWarning)
warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

# feel free to modify, for example, change the context to "notebook"
sns.set_theme(context="talk", style="whitegrid",
              palette="colorblind", color_codes=True,
              rc={"figure.figsize": [12, 8]})

"""# Chapter 11 - Bonus content

In the first edition of the book, we have explored the performance of the 1/n portfolio using the `pyfolio` library. However, since that time the company that was responsible for the library (Quantopian) was closed, and the library is not actively maintained anymore. The library still works, as you can see in the cells below. Alternatively, you can use the `pyfolio-reloaded`, which is a fork of the original library maintained by Stefan Jansen, the author of *Machine Learning for Algorithmic Trading*. On a side note, he is also the maintainer of `zipline-reloaded`, which is a fork of one of the most popular backtesting libraries, which shared the exact same fate as `pyfolio`. You can find the link to `pyfolio-reloaded` below:

* https://github.com/stefan-jansen/pyfolio-reloaded

## 11.1 Evaluating the performance of a basic 1/n portfolio

### How to do it...

1. Import the libraries:
"""

import yfinance as yf
import numpy as np
import pandas as pd
import pyfolio as pf

"""2. Set up the parameters:"""

RISKY_ASSETS = ["FB", "AMZN", "AAPL", "NFLX", "GOOG"]
START_DATE = "2020-01-01"
END_DATE = "2021-12-31"

n_assets = len(RISKY_ASSETS)

"""3. Download the stock prices from Yahoo Finance:"""

prices_df = yf.download(RISKY_ASSETS, start=START_DATE,
                        end=END_DATE, adjusted=True)
prices_df["Adj Close"].plot(title="FAANG stocks in 2020-2021");

sns.despine()
plt.tight_layout()

"""4. Calculate individual asset returns:"""

returns = prices_df["Adj Close"].pct_change().dropna()

"""5. Define the weights:"""

portfolio_weights = n_assets * [1 / n_assets]

"""6. Calculate portfolio returns:"""

portfolio_returns = pd.Series(np.dot(portfolio_weights, returns.T),
                              index=returns.index)

"""7. Create the tear sheet (simple variant):"""

pf.create_simple_tear_sheet(portfolio_returns)

"""### There's more"""

pf.create_returns_tear_sheet(portfolio_returns)